
name: CI

on:
  schedule:
  - cron: "0 11,23 * * 1-5"
  - cron: "0 9,23 * * 6"
  - cron: "0 4,23 * * 0"
  workflow_dispatch:

jobs:
  CI_check:
    runs-on: ubuntu-latest

    steps:
      - uses: cybozu/octoken-action@v1
        id: create-iat
        with:
          github_app_id: ${{ secrets.GH_APP_READ_ALL_ID }}
          github_app_private_key: ${{ secrets.GH_APP_READ_ALL_PRIVATE_KEY }}
        env:
          OPENSSL_CONF: /dev/null
      - uses: actions/checkout@v4
        with:
          token: ${{steps.create-iat.outputs.token}}
          submodules: recursive
          persist-credentials: false
      - name: pull container
        run: |
          docker pull ghcr.io/neyagawarobocons/robo_env_container:latest
      - name: colcon build
        run: |
          docker run --workdir=/ROS_ws\
          --volume=ROS_ws:/ROS_ws ghcr.io/neyagawarobocons/robo_env_container:latest \
          colcon build
