
name: CI

on:
  schedule:
  - cron: "0 11,23 * * 1-5"
  - cron: "0 9,23 * * 6"
  - cron: "0 4,23 * * 0"
  workflow_dispatch:

jobs:
  CI_check:
    runs-on: ghcr.io/neyagawarobocons/robo_env_container:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodule: recursive
      - run: |
          cd ROS_ws
          colcon build
